# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b90ea70e2c0d61ff5e38fbc1ebdbc5d8ef8175411ff96c188ceabce07a79dc99f7415f4a96c997f37f96a82c0a831e413626b163247fa814bfaa0f9e332513d5

test:
  secret_key_base: cddeedcbf3d53ca48712ee624623d6ce5691bf13402fcb493029362607b93ed2c40e8f349d30d59b737be294a2f04dc9027e9554bc0d5fe86c75e7dc5f107970

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
